name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs: 
  pipeline:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI_TEST }}

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "25.8.0"
        cache: "npm"

    - name: Instala dependências
      run: npm ci

    - name: Testar conexão com o MongoDB
      run: |
        node --input-type=module <<'EOF'
        import mongoose from "mongoose";

        try {
          await mongoose.connect(process.env.MONGO_URI, {
            serverSelectionTimeoutMS: 10000
          });

          console.log("Conexão com MongoDB realizada com sucesso");

          await mongoose.disconnect();
        } catch (error) {
          console.error("Erro ao conectar no MongoDB");
          console.error(error.message);
          process.exit(1);
        }
        EOF
        
    - name: Executa testes automatizados
      run: npm test