name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs: 
  pipeline:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI_TEST }}

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "25.8.0"
        cache: "npm"

    - name: Instala dependências
      run: npm ci

    - name: Verificar variável do MongoDB
      run: |
        if [ -z "$MONGO_URI" ]; then
          echo "MONGO_URI não foi configurada"
          exit 1
        else
          echo "MONGO_URI configurada"
        fi

    - name: Executa testes automatizados
      run: npm test